iinfo:
    title: Mkconlife's blog
theme:
    switch: true
    default: style-light
favicon:
    #logo: /img/logo.png
    visibilitychange: true
    hidden: failure.ico
    showText: 欢迎回来
    hideText: 快回来QAQ
user:
    name: Mkconlife
    email: 3297602270@qq.com
    domain: https://mkconlife.github.io
    avatar: /img/avatar.jpg
    describe: 
top_bars:
    - title: home
      url: /
      children:
    - title: archives
      url: /archives/
      noswup: true
    - title: links
      url: /links/
      noswup: true
sidebar:
    social: 
    typedText: ["a middle school student"]
    info: # 个人信息
        - key: 地址
          val: 银河系
        - key: 年龄
          val: 16
lazyload:
    enable: true
banner:
    index:
        type: img
        bgrul: /img/wallpaper.jpg
        bannerTitle: Welcome,<br>My friend!
        bannerText: 我们沙沙作响的树叶用自己的声音来回答狂风暴雨。而沉默的你是谁？我不过是一朵小小的花。
footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 05/01/2023 9:32:16
  custom_text:
toc:
    enable: true
    list_number: true
    max_depth: 3
    min_depth: 1
post_pagination:
    enable: true
    type: small 
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:
  wrap: true
  hljs: true
  theme: mac # 使用mac主题

code:
  font_size: 14px
  font_family: Monaco, Menlo, Consolas
  padding: 10px
  background_color: #f6f8fa # 设置背景颜色，可以根据自己的喜好进行调整
  border_radius: 5px
  box_shadow: none
  line_height: 1.5
  overflow: auto

datetime_foramt:
    post_card:
        date: YY/MM/DD
        time: HH:mm
    post_info:
        date: MM/DD
        time: HH:mm
    archive:
        date: MM/DD
        time: HH:mm
rightside:
    readmode: true
    aside: true
wordcount:
  enable: true
  count: true
  time: true
aplayer:
  enable: true # Whether to enable
  type: fixed # fixed, mini
  audios:
    - name: Welt Joyce
      artist: HOYO-MIX
      url: /music/welt-joyce.mp3       
      cover: /music/picture/welt-joyce.png